require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
FirebaseSDKVersion = '7.7.0'
RNFirebaseAsStaticFramework = true

target 'Diva' do
  # config = use_native_modules!
#   react_native_path = ENV["REACT_NATIVE_PATH"]
#   config = {
#   "reactNativePath" => react_native_path
# }
#   use_react_native!(:path => config["reactNativePath"])

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-restart', :path => '../node_modules/react-native-restart'

  # pod 'react-native-fbsdk-next', :path => '../node_modules/react-native-fbsdk-next'


  target 'DivaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

post_install do |installer|
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(inherited)', '$(SDKROOT)/usr/lib/swift']
        end
      end
    end
  end

target 'Diva-tvOS' do
  # Pods for Diva-tvOS

  target 'Diva-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
